version: '3.9'

services:
  db:
    image: postgres:16.3
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network
    container_name: postgres_db

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - network
    container_name: redis

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    working_dir: /backend
    ports:
      - "8000:8000"
    networks:
      - network
    container_name: backend

  daphne:
    build:
      context: ./backend/
      dockerfile: Dockerfile.daphne
    container_name: 'daphne'
    volumes:
      - ./backend/:/app/backend/
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8001:8001"
    networks:
      - network


volumes:
  postgres_data:

networks:
  network:
    name: network
    driver: bridge