# Generated by Django 5.0.6 on 2024-05-20 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user1_score", models.IntegerField(default=0)),
                ("user2_score", models.IntegerField(default=0)),
                (
                    "game_type",
                    models.CharField(
                        choices=[("TYPE1", "Local Game"), ("TYPE2", "Multi Game")],
                        max_length=10,
                    ),
                ),
                (
                    "user_id1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_as_user1",
                        to="user.member",
                    ),
                ),
                (
                    "user_id2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_as_user2",
                        to="user.member",
                    ),
                ),
            ],
        ),
    ]
