# Generated by Django 5.0.6 on 2024-05-21 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("LOCAL", "Local Game"),
                    ("REMOTE", "Remote Game"),
                    ("TOURNAMENT", "Tournament Game"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="user1_score",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="user2_score",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
