# Generated by Django 3.2.13 on 2024-05-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20240530_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
