# Generated by Django 5.0.6 on 2024-05-21 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_game_game_type_alter_game_user1_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="user_id1",
            new_name="user1_id",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="user_id2",
            new_name="user2_id",
        ),
        migrations.AddField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
