# Generated by Django 3.2.13 on 2024-05-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_user_id1_game_user1_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='user1_id',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='user2_id',
            new_name='user2',
        ),
    ]
